### ISSUE TITLE
Proposal: Modularized Plugin Architecture

### ISSUE THREAD

**Issue by ghost** [benprime/crucible-mud#73]
We're considering re-organzing the tree structure and architecture to follow a plugin structure. Where groups of commands will be defined in a plugin, along with any supporting code. This will better organize the tree structure and allow for plugins to be enabled and disabled.

A sample tree structure follows:
```
/plugins
  /combat
    /commands
    /events? (events to register to the room)
    /intervalSetups? (modules can have their own game loops)
    index.js
```

Plugins would need to be able to interact. For exammple: For features such as "Party" and "Combat", we would need to determine how plugins would interoperate. For instance, in the party feature, there is a command to "backrank" that would allow a player to be hit less often. If the party feature is optional, and can be turned off and on, then we would need a pattern that would allow for abstracting the entity being attacked, so that mobs selecting an attack target can be plugin agnostic.

As a rule, plugins should not be able to be aware of other plugins. There should not be a feature where a plugin has to register itself with another. To that end, we're going to need to come up with a core framework that allows for some kind of centralized registration of events. Let's discuss.

```
Command organization:

- World Building -
create
destroy
set
list
spawner

- Admin support -
spawn
summon
teleport

-Core-
help
look
who


- Communication -
telepathy
say
gossip
yell

- Combat -
attack
break
exp

- Movement -
move
close
lock
open
unlock

- Inventory -
inventory
drop
equip
unequip
keys
take
offer
```

**Comment by benprime** [comment]
Completed.
